telegram:
  bot:
    #    не вписывайте данные, так как можете отправить в публичный репозиторий
    #    используйте переменные среды для установки значений
    username: FarEastCryptoBot
    token: 7725391656:AAFvxFgSxGs3QF0OflIoKUyioJdb3pC0HN0
    notify:
      delay:
        value: 10
        unit: MINUTES

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 30091998As!
    url: jdbc:postgresql://localhost:5432/crypto_bot
    username: postgres


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: create
    show-sql: true

message-text-configuration:
  start-command-identifier: "start"
  start-command-description: "Запускает бота"
  start-greetings-message: |
    Привет! Данный бот помогает отслеживать стоимость биткоина.
    Поддерживаемые команды:
     /subscribe [число] - подписаться на стоимость биткоина в USD
     /get_price - получить стоимость биткоина
     /get_subscription - получить текущую подписку
     /unsubscribe - отменить подписку на стоимость
  start-error-message: "Error occurred in /start command"

  get-price-command-identifier: "get_price"
  get-price-command-description: "Возвращает цену биткоина в USD"
  get-price-message: "Текущая цена биткоина %.2f USD"
  get-price-error-message: "Ошибка возникла /get_price методе"
  get-price-disconnect-message: "Соединение c интернетом потерянно"

  subscribe-command-identifier: "subscribe"
  subscribe-command-description: "Подписывает пользователя на стоимость биткоина"
  subscribe-wrong-input-message: "Неверный формат ввода"
  subscribe-message: "Новая подписка создана на стоимость USD"
  subscribe-error-message: "Error occurred in /subscribe command"

  get-subscription-command-identifier: "get_subscription"
  get-subscription-command-description: "Возвращает текущую подписку"
  get-non-active-subscription-message: "Активные подписки отсутствуют"
  get-subscription-message: "Вы подписаны на стоимость биткоина %.2f USD"
  get-subscription-error-message: "Error occurred in /get_subscription command"

  unsubscribe-message: "Подписка отменена"
  unsubscribe-error-message: "Error occurred in /unsubscribe command"

  check-notification: "Пора покупать, стоимость биткоина %.2f USD"


pattern-configuration:
  regexes:
    - "\\s\\[(\\d+)\\]\\s?"
    - "\\s(\\d+)\\s?"
    - "\\s\\((\\d+)\\)\\s?"
    - "\\s\\{(\\d+)\\}\\s?"


checking-configuration:
  checking-frequency: 2
  notification-frequency: 10
  delay: 10