telegram:
  bot:
    #    не вписывайте данные, так как можете отправить в публичный репозиторий
    #    используйте переменные среды для установки значений
    username: FarEastCryptoBot
    token: 7725391656:AAFvxFgSxGs3QF0OflIoKUyioJdb3pC0HN0
    notify:
      delay:
        value: 10
        unit: MINUTES

binance:
  api:
    getPrice: https://api.binance.com/api/v3/avgPrice?symbol=BTCUSDT


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 30091998As!
    url: jdbc:postgresql://localhost:5432/crypto_bot
    username: postgres


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: create
    show-sql: true

message-text-configuration:
  start-greetings-message: """
                Привет! Данный бот помогает отслеживать стоимость биткоина.
                Поддерживаемые команды:
                 /subscribe [число] - подписаться на стоимость биткоина в USD
                 /get_price - получить стоимость биткоина
                 /get_subscription - получить текущую подписку
                 /unsubscribe - отменить подписку на стоимость
                """
  start-error-message: "Error occurred in /start command"
  get-price-message: "Текущая цена биткоина USD"
  get-price-error-message: "Ошибка возникла /get_price методе"
  subscribe-wrong-input-message: "Неверный формат ввода"
  subscribe-message: "Новая подписка создана на стоимость USD"
  subscribe-error-message: "Error occurred in /subscribe command"
  get-non-active-subscription-message: "Активные подписки отсутствуют"
  get-subscription-message: "Вы подписаны на стоимость биткоина USD"
  get-subscription-error-message: "Error occurred in /get_subscription command"
  unsubscribe-message: "Подписка отменена"
  unsubscribe-error-message: "Error occurred in /unsubscribe command"


pattern-configuration:
  regexes:
    - "\\s\\[(\\d+)\\]\\s?"
    - "\\s(\\d+)\\s?"
    - "\\s\\((\\d+)\\)\\s?"
    - "\\s\\{(\\d+)\\}\\s?"
